-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7mtVGUv/5LotVXNg
DBHLafJPPvBsK8Cv/ci2IiEplk6gCgYIKoZIzj0DAQehRANCAARUcUxthzN0NksN
klYClcu2nvxOwFBMZbXfmfKBLu9T9x9/XeKnuQ91Q/BJgx3sy3yEyyoArssfPSGL
ZrQ6Y7uM
-----END PRIVATE KEY-----