-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghrDHaYWMPmZWn9b2
NhHK5+ubPPMuvN/oTExUAPk3MxKgCgYIKoZIzj0DAQehRANCAATeRCywBcH+Fr24
NOp2K+nx+K8g/dEQEm+xO29t5ReYI0l/xlUyDXCrI9Z84R3xUfdhz+nnwKkqaT5N
oAmb2sBx
-----END PRIVATE KEY-----