-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoyCIhvsgIonTSs2H
RDOcq/PCgyOkahHidy95UGjiwgGgCgYIKoZIzj0DAQehRANCAARCBHBZrf+KnrKp
9YV1vnmrScAwphc5WdXtCizrfIOCULRcwLjR1294t7qkK0Ga7M2ZiujwvUricFZz
VRyTQlfQ
-----END PRIVATE KEY-----