-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjLNAGuplxHg4Ic+/
tW0f+vsbbHGW+SnmKA0PFtEA+fKgCgYIKoZIzj0DAQehRANCAAQ3kKkTec4eHNLK
60YgSItMVqccUsiimTA6PYmscrJwejHLOcJNvCIfXU4YVKqU5GjXJkAyk4TDiuc2
1R5GRx1V
-----END PRIVATE KEY-----