-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2DOAqXftk4Vne+Ie
kTneZVtPCTwl4M2c0T1bkjjHlcCgCgYIKoZIzj0DAQehRANCAAS7MkYyQkU7CYNn
FdWqXQFPguO6aO1elWxf5xGveybNqmgABcey0m1I4ECdFR+B1XalLzeUejkHGhcf
H1Y4TFWh
-----END PRIVATE KEY-----