-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTYml3lYSMSkn5z//
Zc0apPAIMPNc9Ie4jnvn33XDIdmgCgYIKoZIzj0DAQehRANCAASDBJg9zmz6d1Bd
4/Cz7E/ch5Xn+P8QnctZE5wpOmjXwswkGDCQK+AS6U9Rec4DHZDsssLKCJKjLGDM
JYsrsBbS
-----END PRIVATE KEY-----