-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcmDuMcr8V1FYVKms
K2XmKkafD5xx7gxd2obaCpofiyGgCgYIKoZIzj0DAQehRANCAAR7ZG5QhEf+7SDW
vfugDfaQk5ejave1akEl4baqt4By4YsBJEbTjyl2F2TjcLe8dkFtFk0RoCLKre+v
jhddCxOc
-----END PRIVATE KEY-----