-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQge/AtlTzF2KquywKO
8u4SWB5iabIB5vPjNL1I7M5TaVygCgYIKoZIzj0DAQehRANCAAS6zCGBapAo2BSP
SC+Z3aDSdj9FVlRUBSJ2XinUqbVCtKFRJGdUuPDojsEP4fqcC9lbnnqSpaEVZAFU
XRSh34OR
-----END PRIVATE KEY-----