-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMa/nvnkC/3fH7Fgi
6vwKU0phKzwTbEsowEQPAhvFv3SgCgYIKoZIzj0DAQehRANCAATBScyl7bMlMBjU
hq3mB80m+ZW/deCx7CASpgLYG6iKoGZ1dOINqhP9/2nnkq0bVay+DXPba00so2ql
NLyQHRVS
-----END PRIVATE KEY-----