-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFjRZh+hgEGqlmRA0
ZIKEpwfTGnLroRi2fKgxhfXFy8igCgYIKoZIzj0DAQehRANCAARGZD1Mu4uJILyP
Q9GZLZsJFvvfAz/YAR5nBR4mZZuUcKwbfqIwS5vszbiW5CX6hqoecVKUTwBNGa7s
OC4qy3dg
-----END PRIVATE KEY-----