-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQ5uPTAbJ7lPM5hNG
mHB+HixjFHvbKv0kDZs+UTcts9KgCgYIKoZIzj0DAQehRANCAAQ8hBndxtnqJkl8
gbd18cAkQ4a/nBBig4LHM5MOTXhOwxug2ID8yrKgDYR/G2AQm8bUDD98jayfjQ+h
c7o1Thzh
-----END PRIVATE KEY-----