-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0M5Zjg3yeZB3lw2y
z9CdUqYuj9mWaREYGOFmo/2zDCqgCgYIKoZIzj0DAQehRANCAASlDyuMRatXLCZa
ARAWtaa0OzL0vOP1WF0gT+5mFck5fxNezUgFCNTQNVTBwYqBRnrxQvMPaE3DOh0u
Hb6/Hd6f
-----END PRIVATE KEY-----