-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMth4qrZbsSbsSedc
1Yr+oBMWYOTA0YlcMnJYfSo2D+mgCgYIKoZIzj0DAQehRANCAAQZ6TlYsCMwnW6D
6MQqgjR78Ytz4Zuuqx58gGpLuEBT/wRBH+ImJx8/gTjlUaJK0PmOkwKxrEjZd7jX
4glLAPdy
-----END PRIVATE KEY-----