-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZRede2HEvTIo00w9
NphK0/2Jzsd/K18qvb6qKSHcMYKgCgYIKoZIzj0DAQehRANCAAQywpdWF6GifeRT
dLsas1s9/7/SiUhSgo05jrZkjcO1raVJBPJZooVVQqQCOaKGMkrp+K+DQeurm9Op
UiU/u0JM
-----END PRIVATE KEY-----