-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrkBzaHlHOmf+BlK0
QMJbn/g97/gP3RdHmnQhgI0fXlSgCgYIKoZIzj0DAQehRANCAAQWa9gZnspDrhUx
4u7PnweOfYurRDCbwZmCwJBDvsFX/BypoOs8OvUEdZVxP0TaFasTxqX7UF0TNtR9
QuXfc25b
-----END PRIVATE KEY-----