-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgd+oFnEJ0fwE2Iexz
Dfw9QnvGqPgPZ7C7UgdR7tvPUcGgCgYIKoZIzj0DAQehRANCAASMYFdgHAF7aZQd
sqDMw4b/nLRNRv1fzFB9KnfvToKzk4WXl6sf0GswX35J53MoMx0yFti3hSjekRtM
YPmdhQbm
-----END PRIVATE KEY-----