-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmaSqQoYSCCsYGaSd
wJLHiatYFZSyn4uJiiifcjPY19WgCgYIKoZIzj0DAQehRANCAAR4oyDLoXegr3d/
wB7UVYJmLwiF3r1OFh4c/VZGRvY6rSkCI44DJ8bTCnHOzyE0eQ+IfzpXb2RIpi8Q
4bTU1+iE
-----END PRIVATE KEY-----