-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglgeeKtZY21Q1YlF1
oKnDFoRxFlfJh56Dct8oujpawf2gCgYIKoZIzj0DAQehRANCAAQmrJAUNGqntvxE
RWNSy8H1LRKg9Gk8w8tAFvexBRtPihZhnaTwX3dFKX3hguugCWVVCKLYX1Sr2k90
WQngTxbX
-----END PRIVATE KEY-----